# docker-compose.yaml

version: '3.8'
services:
  product-catalogue-service:
    build:
      context: ./product-catalog-service
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/boutique
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/boutique
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boutique
    volumes:
      - db_init:/docker-entrypoint-initdb.d/ 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database/data
  db_init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database/sql
